/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMatrikelRouteImport } from './routes/api/matrikel'
import { Route as AuthenticatedVedligeholdRouteImport } from './routes/_authenticated/vedligehold'
import { Route as AuthenticatedOverblikRouteImport } from './routes/_authenticated/overblik'
import { Route as AuthenticatedLeverandoererRouteImport } from './routes/_authenticated/leverandoerer'
import { Route as AuthenticatedLandbrugsjordRouteImport } from './routes/_authenticated/landbrugsjord'
import { Route as AuthenticatedKunderRouteImport } from './routes/_authenticated/kunder'
import { Route as AuthenticatedJagtlejeRouteImport } from './routes/_authenticated/jagtleje'
import { Route as AuthenticatedFakturakladderRouteImport } from './routes/_authenticated/fakturakladder'
import { Route as AuthenticatedDokumenterRouteImport } from './routes/_authenticated/dokumenter'
import { Route as AuthenticatedBygningerRouteImport } from './routes/_authenticated/bygninger'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as ApiDineroExportInvoiceRouteImport } from './routes/api/dinero/export-invoice'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatrikelRoute = ApiMatrikelRouteImport.update({
  id: '/api/matrikel',
  path: '/api/matrikel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVedligeholdRoute =
  AuthenticatedVedligeholdRouteImport.update({
    id: '/vedligehold',
    path: '/vedligehold',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverblikRoute = AuthenticatedOverblikRouteImport.update({
  id: '/overblik',
  path: '/overblik',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeverandoererRoute =
  AuthenticatedLeverandoererRouteImport.update({
    id: '/leverandoerer',
    path: '/leverandoerer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandbrugsjordRoute =
  AuthenticatedLandbrugsjordRouteImport.update({
    id: '/landbrugsjord',
    path: '/landbrugsjord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKunderRoute = AuthenticatedKunderRouteImport.update({
  id: '/kunder',
  path: '/kunder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJagtlejeRoute = AuthenticatedJagtlejeRouteImport.update({
  id: '/jagtleje',
  path: '/jagtleje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFakturakladderRoute =
  AuthenticatedFakturakladderRouteImport.update({
    id: '/fakturakladder',
    path: '/fakturakladder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDokumenterRoute = AuthenticatedDokumenterRouteImport.update({
  id: '/dokumenter',
  path: '/dokumenter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBygningerRoute = AuthenticatedBygningerRouteImport.update({
  id: '/bygninger',
  path: '/bygninger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDineroExportInvoiceRoute = ApiDineroExportInvoiceRouteImport.update({
  id: '/api/dinero/export-invoice',
  path: '/api/dinero/export-invoice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/bygninger': typeof AuthenticatedBygningerRoute
  '/dokumenter': typeof AuthenticatedDokumenterRoute
  '/fakturakladder': typeof AuthenticatedFakturakladderRoute
  '/jagtleje': typeof AuthenticatedJagtlejeRoute
  '/kunder': typeof AuthenticatedKunderRoute
  '/landbrugsjord': typeof AuthenticatedLandbrugsjordRoute
  '/leverandoerer': typeof AuthenticatedLeverandoererRoute
  '/overblik': typeof AuthenticatedOverblikRoute
  '/vedligehold': typeof AuthenticatedVedligeholdRoute
  '/api/matrikel': typeof ApiMatrikelRoute
  '/api/dinero/export-invoice': typeof ApiDineroExportInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/bygninger': typeof AuthenticatedBygningerRoute
  '/dokumenter': typeof AuthenticatedDokumenterRoute
  '/fakturakladder': typeof AuthenticatedFakturakladderRoute
  '/jagtleje': typeof AuthenticatedJagtlejeRoute
  '/kunder': typeof AuthenticatedKunderRoute
  '/landbrugsjord': typeof AuthenticatedLandbrugsjordRoute
  '/leverandoerer': typeof AuthenticatedLeverandoererRoute
  '/overblik': typeof AuthenticatedOverblikRoute
  '/vedligehold': typeof AuthenticatedVedligeholdRoute
  '/api/matrikel': typeof ApiMatrikelRoute
  '/api/dinero/export-invoice': typeof ApiDineroExportInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/bygninger': typeof AuthenticatedBygningerRoute
  '/_authenticated/dokumenter': typeof AuthenticatedDokumenterRoute
  '/_authenticated/fakturakladder': typeof AuthenticatedFakturakladderRoute
  '/_authenticated/jagtleje': typeof AuthenticatedJagtlejeRoute
  '/_authenticated/kunder': typeof AuthenticatedKunderRoute
  '/_authenticated/landbrugsjord': typeof AuthenticatedLandbrugsjordRoute
  '/_authenticated/leverandoerer': typeof AuthenticatedLeverandoererRoute
  '/_authenticated/overblik': typeof AuthenticatedOverblikRoute
  '/_authenticated/vedligehold': typeof AuthenticatedVedligeholdRoute
  '/api/matrikel': typeof ApiMatrikelRoute
  '/api/dinero/export-invoice': typeof ApiDineroExportInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/budget'
    | '/bygninger'
    | '/dokumenter'
    | '/fakturakladder'
    | '/jagtleje'
    | '/kunder'
    | '/landbrugsjord'
    | '/leverandoerer'
    | '/overblik'
    | '/vedligehold'
    | '/api/matrikel'
    | '/api/dinero/export-invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/budget'
    | '/bygninger'
    | '/dokumenter'
    | '/fakturakladder'
    | '/jagtleje'
    | '/kunder'
    | '/landbrugsjord'
    | '/leverandoerer'
    | '/overblik'
    | '/vedligehold'
    | '/api/matrikel'
    | '/api/dinero/export-invoice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/budget'
    | '/_authenticated/bygninger'
    | '/_authenticated/dokumenter'
    | '/_authenticated/fakturakladder'
    | '/_authenticated/jagtleje'
    | '/_authenticated/kunder'
    | '/_authenticated/landbrugsjord'
    | '/_authenticated/leverandoerer'
    | '/_authenticated/overblik'
    | '/_authenticated/vedligehold'
    | '/api/matrikel'
    | '/api/dinero/export-invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiMatrikelRoute: typeof ApiMatrikelRoute
  ApiDineroExportInvoiceRoute: typeof ApiDineroExportInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matrikel': {
      id: '/api/matrikel'
      path: '/api/matrikel'
      fullPath: '/api/matrikel'
      preLoaderRoute: typeof ApiMatrikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vedligehold': {
      id: '/_authenticated/vedligehold'
      path: '/vedligehold'
      fullPath: '/vedligehold'
      preLoaderRoute: typeof AuthenticatedVedligeholdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overblik': {
      id: '/_authenticated/overblik'
      path: '/overblik'
      fullPath: '/overblik'
      preLoaderRoute: typeof AuthenticatedOverblikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leverandoerer': {
      id: '/_authenticated/leverandoerer'
      path: '/leverandoerer'
      fullPath: '/leverandoerer'
      preLoaderRoute: typeof AuthenticatedLeverandoererRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landbrugsjord': {
      id: '/_authenticated/landbrugsjord'
      path: '/landbrugsjord'
      fullPath: '/landbrugsjord'
      preLoaderRoute: typeof AuthenticatedLandbrugsjordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunder': {
      id: '/_authenticated/kunder'
      path: '/kunder'
      fullPath: '/kunder'
      preLoaderRoute: typeof AuthenticatedKunderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jagtleje': {
      id: '/_authenticated/jagtleje'
      path: '/jagtleje'
      fullPath: '/jagtleje'
      preLoaderRoute: typeof AuthenticatedJagtlejeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fakturakladder': {
      id: '/_authenticated/fakturakladder'
      path: '/fakturakladder'
      fullPath: '/fakturakladder'
      preLoaderRoute: typeof AuthenticatedFakturakladderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokumenter': {
      id: '/_authenticated/dokumenter'
      path: '/dokumenter'
      fullPath: '/dokumenter'
      preLoaderRoute: typeof AuthenticatedDokumenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bygninger': {
      id: '/_authenticated/bygninger'
      path: '/bygninger'
      fullPath: '/bygninger'
      preLoaderRoute: typeof AuthenticatedBygningerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/dinero/export-invoice': {
      id: '/api/dinero/export-invoice'
      path: '/api/dinero/export-invoice'
      fullPath: '/api/dinero/export-invoice'
      preLoaderRoute: typeof ApiDineroExportInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedBygningerRoute: typeof AuthenticatedBygningerRoute
  AuthenticatedDokumenterRoute: typeof AuthenticatedDokumenterRoute
  AuthenticatedFakturakladderRoute: typeof AuthenticatedFakturakladderRoute
  AuthenticatedJagtlejeRoute: typeof AuthenticatedJagtlejeRoute
  AuthenticatedKunderRoute: typeof AuthenticatedKunderRoute
  AuthenticatedLandbrugsjordRoute: typeof AuthenticatedLandbrugsjordRoute
  AuthenticatedLeverandoererRoute: typeof AuthenticatedLeverandoererRoute
  AuthenticatedOverblikRoute: typeof AuthenticatedOverblikRoute
  AuthenticatedVedligeholdRoute: typeof AuthenticatedVedligeholdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedBygningerRoute: AuthenticatedBygningerRoute,
  AuthenticatedDokumenterRoute: AuthenticatedDokumenterRoute,
  AuthenticatedFakturakladderRoute: AuthenticatedFakturakladderRoute,
  AuthenticatedJagtlejeRoute: AuthenticatedJagtlejeRoute,
  AuthenticatedKunderRoute: AuthenticatedKunderRoute,
  AuthenticatedLandbrugsjordRoute: AuthenticatedLandbrugsjordRoute,
  AuthenticatedLeverandoererRoute: AuthenticatedLeverandoererRoute,
  AuthenticatedOverblikRoute: AuthenticatedOverblikRoute,
  AuthenticatedVedligeholdRoute: AuthenticatedVedligeholdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiMatrikelRoute: ApiMatrikelRoute,
  ApiDineroExportInvoiceRoute: ApiDineroExportInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
