/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLandbrugsjordRouteImport } from './routes/_authenticated/landbrugsjord'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBygningerRouteImport } from './routes/_authenticated/bygninger'
import { Route as AuthenticatedSkovOverblikRouteImport } from './routes/_authenticated/skov.overblik'
import { Route as AuthenticatedSkovHugstRouteImport } from './routes/_authenticated/skov.hugst'
import { Route as AuthenticatedHalmSalgRouteImport } from './routes/_authenticated/halm.salg'
import { Route as AuthenticatedHalmOekonomiRouteImport } from './routes/_authenticated/halm.oekonomi'
import { Route as AuthenticatedHalmLagerRouteImport } from './routes/_authenticated/halm.lager'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLandbrugsjordRoute =
  AuthenticatedLandbrugsjordRouteImport.update({
    id: '/landbrugsjord',
    path: '/landbrugsjord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBygningerRoute = AuthenticatedBygningerRouteImport.update({
  id: '/bygninger',
  path: '/bygninger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkovOverblikRoute =
  AuthenticatedSkovOverblikRouteImport.update({
    id: '/skov/overblik',
    path: '/skov/overblik',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkovHugstRoute = AuthenticatedSkovHugstRouteImport.update({
  id: '/skov/hugst',
  path: '/skov/hugst',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHalmSalgRoute = AuthenticatedHalmSalgRouteImport.update({
  id: '/halm/salg',
  path: '/halm/salg',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHalmOekonomiRoute =
  AuthenticatedHalmOekonomiRouteImport.update({
    id: '/halm/oekonomi',
    path: '/halm/oekonomi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHalmLagerRoute = AuthenticatedHalmLagerRouteImport.update({
  id: '/halm/lager',
  path: '/halm/lager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bygninger': typeof AuthenticatedBygningerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/landbrugsjord': typeof AuthenticatedLandbrugsjordRoute
  '/halm/lager': typeof AuthenticatedHalmLagerRoute
  '/halm/oekonomi': typeof AuthenticatedHalmOekonomiRoute
  '/halm/salg': typeof AuthenticatedHalmSalgRoute
  '/skov/hugst': typeof AuthenticatedSkovHugstRoute
  '/skov/overblik': typeof AuthenticatedSkovOverblikRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bygninger': typeof AuthenticatedBygningerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/landbrugsjord': typeof AuthenticatedLandbrugsjordRoute
  '/halm/lager': typeof AuthenticatedHalmLagerRoute
  '/halm/oekonomi': typeof AuthenticatedHalmOekonomiRoute
  '/halm/salg': typeof AuthenticatedHalmSalgRoute
  '/skov/hugst': typeof AuthenticatedSkovHugstRoute
  '/skov/overblik': typeof AuthenticatedSkovOverblikRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bygninger': typeof AuthenticatedBygningerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/landbrugsjord': typeof AuthenticatedLandbrugsjordRoute
  '/_authenticated/halm/lager': typeof AuthenticatedHalmLagerRoute
  '/_authenticated/halm/oekonomi': typeof AuthenticatedHalmOekonomiRoute
  '/_authenticated/halm/salg': typeof AuthenticatedHalmSalgRoute
  '/_authenticated/skov/hugst': typeof AuthenticatedSkovHugstRoute
  '/_authenticated/skov/overblik': typeof AuthenticatedSkovOverblikRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bygninger'
    | '/dashboard'
    | '/landbrugsjord'
    | '/halm/lager'
    | '/halm/oekonomi'
    | '/halm/salg'
    | '/skov/hugst'
    | '/skov/overblik'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bygninger'
    | '/dashboard'
    | '/landbrugsjord'
    | '/halm/lager'
    | '/halm/oekonomi'
    | '/halm/salg'
    | '/skov/hugst'
    | '/skov/overblik'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bygninger'
    | '/_authenticated/dashboard'
    | '/_authenticated/landbrugsjord'
    | '/_authenticated/halm/lager'
    | '/_authenticated/halm/oekonomi'
    | '/_authenticated/halm/salg'
    | '/_authenticated/skov/hugst'
    | '/_authenticated/skov/overblik'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/landbrugsjord': {
      id: '/_authenticated/landbrugsjord'
      path: '/landbrugsjord'
      fullPath: '/landbrugsjord'
      preLoaderRoute: typeof AuthenticatedLandbrugsjordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bygninger': {
      id: '/_authenticated/bygninger'
      path: '/bygninger'
      fullPath: '/bygninger'
      preLoaderRoute: typeof AuthenticatedBygningerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skov/overblik': {
      id: '/_authenticated/skov/overblik'
      path: '/skov/overblik'
      fullPath: '/skov/overblik'
      preLoaderRoute: typeof AuthenticatedSkovOverblikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skov/hugst': {
      id: '/_authenticated/skov/hugst'
      path: '/skov/hugst'
      fullPath: '/skov/hugst'
      preLoaderRoute: typeof AuthenticatedSkovHugstRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/halm/salg': {
      id: '/_authenticated/halm/salg'
      path: '/halm/salg'
      fullPath: '/halm/salg'
      preLoaderRoute: typeof AuthenticatedHalmSalgRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/halm/oekonomi': {
      id: '/_authenticated/halm/oekonomi'
      path: '/halm/oekonomi'
      fullPath: '/halm/oekonomi'
      preLoaderRoute: typeof AuthenticatedHalmOekonomiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/halm/lager': {
      id: '/_authenticated/halm/lager'
      path: '/halm/lager'
      fullPath: '/halm/lager'
      preLoaderRoute: typeof AuthenticatedHalmLagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBygningerRoute: typeof AuthenticatedBygningerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLandbrugsjordRoute: typeof AuthenticatedLandbrugsjordRoute
  AuthenticatedHalmLagerRoute: typeof AuthenticatedHalmLagerRoute
  AuthenticatedHalmOekonomiRoute: typeof AuthenticatedHalmOekonomiRoute
  AuthenticatedHalmSalgRoute: typeof AuthenticatedHalmSalgRoute
  AuthenticatedSkovHugstRoute: typeof AuthenticatedSkovHugstRoute
  AuthenticatedSkovOverblikRoute: typeof AuthenticatedSkovOverblikRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBygningerRoute: AuthenticatedBygningerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLandbrugsjordRoute: AuthenticatedLandbrugsjordRoute,
  AuthenticatedHalmLagerRoute: AuthenticatedHalmLagerRoute,
  AuthenticatedHalmOekonomiRoute: AuthenticatedHalmOekonomiRoute,
  AuthenticatedHalmSalgRoute: AuthenticatedHalmSalgRoute,
  AuthenticatedSkovHugstRoute: AuthenticatedSkovHugstRoute,
  AuthenticatedSkovOverblikRoute: AuthenticatedSkovOverblikRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
